#GET
# /api/v1/bootcamps
#Show All Bootcamps
GET http://127.0.0.1:8888/api/v1/bootcamps
###
#POST
# /api/v1/bootcamps
#Create new Bootcamp 
POST http://127.0.0.1:8888/api/v1/bootcamps
###
#PUT
# /api/v1/bootcamps/:id
#Update bootcamp
PUT http://127.0.0.1:8888/api/v1/bootcamps/1

###
#GET
# /api/v1/bootcamps/:id
# Get single bootcamp by id
GET http://127.0.0.1:8888/api/v1/bootcamps/1

###

#DELETE
# /api/v1/bootcamps/:id
# Delete bootcamp by id
DELETE http://127.0.0.1:8888/api/v1/bootcamps/1
